include(FetchContent)
include(FindPackageHandleStandardArgs)

if(DEPENDENCY_EROFS_UTILS_REPOSITORY)
    FetchContent_Declare(erofs-utils
        GIT_REPOSITORY ${DEPENDENCY_EROFS_UTILS_REPOSITORY}
        GIT_TAG        ${DEPENDENCY_EROFS_UTILS_TAG}
    )
    FetchContent_GetProperties(erofs-utils)
    if(NOT erofs-utils_POPULATED)
        FetchContent_Populate(erofs-utils)
    endif()

    set(EROFS_LIB_INCLUDE_DIR "${erofs-utils_SOURCE_DIR}/include/" CACHE PATH "erofs-utils include path.")
    set(EROFS_CONFIG_FILE "${erofs-utils_SOURCE_DIR}/config.h" CACHE PATH "erofs-utils config file.")
    set(EROFS_LIB_STATIC "${erofs-utils_SOURCE_DIR}/lib/.libs/liberofs.a" CACHE PATH "erofs-utils static lib.")

    # liberofs.a and config.h are produced at build time; make sure the include
    # dir exists at configure time so EROFS::utils' INTERFACE_INCLUDE_DIRECTORIES
    # passes CMake's imported-target path validation.
    file(MAKE_DIRECTORY ${EROFS_LIB_INCLUDE_DIR})

    # build erofs-utils with its own autotools at build time (not configure time)
    if(NOT TARGET liberofs_build)
        add_custom_command(
            OUTPUT ${EROFS_LIB_STATIC}
            WORKING_DIRECTORY ${erofs-utils_SOURCE_DIR}
            COMMAND ./autogen.sh &&
                    ./configure --disable-lz4 --disable-lzma --without-libzstd
                        --without-uuid --disable-multithreading &&
                    make)
        add_custom_target(liberofs_build DEPENDS ${EROFS_LIB_STATIC})
    endif()

    set(erofsutils_FOUND yes)
    if(NOT TARGET EROFS::utils)
        add_library(EROFS::utils STATIC IMPORTED)
    endif()
    add_dependencies(EROFS::utils liberofs_build)
else()
    find_path(EROFS_LIB_INCLUDE_DIR erofs/tar.h)
    find_library(EROFS_LIB_STATIC erofs)
    # config.h is generated by erofs-utils' own configure and force-included as
    # a compile option below, so a local installation has to provide it as well
    find_file(EROFS_CONFIG_FILE erofs/config.h)

    find_package_handle_standard_args(erofsutils DEFAULT_MSG EROFS_LIB_STATIC
                                      EROFS_LIB_INCLUDE_DIR EROFS_CONFIG_FILE)

    if(erofsutils_FOUND AND NOT TARGET EROFS::utils)
        add_library(EROFS::utils STATIC IMPORTED)
    endif()
endif()

if(TARGET EROFS::utils)
    set_target_properties(
        EROFS::utils
        PROPERTIES IMPORTED_LINK_INTERFACE_LANGUAGES "C"
                   IMPORTED_LOCATION "${EROFS_LIB_STATIC}"
                   INTERFACE_INCLUDE_DIRECTORIES "${EROFS_LIB_INCLUDE_DIR}"
                   INTERFACE_COMPILE_OPTIONS "-include${EROFS_CONFIG_FILE}")
endif()
