set(CPACK_PACKAGE_VERSION ${PACKAGE_VERSION})
set(CPACK_GENERATOR "RPM;DEB")
set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
if (PACKAGE_RELEASE)
    set(CPACK_PACKAGE_RELEASE ${PACKAGE_RELEASE})
else()
    set(CPACK_PACKAGE_RELEASE "1")
endif()

set(CPACK_PACKAGE_CONTACT "The overlaybd authors")
set(CPACK_PACKAGE_VENDOR "Overlaybd")
set(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_PACKAGE_RELEASE}.${CMAKE_SYSTEM_PROCESSOR}")

set(CPACK_RPM_PACKAGE_LICENSE "Apache v2.0")
set(CPACK_RPM_PACKAGE_RELEASE ${PACKAGE_RELEASE})
set(CPACK_RPM_PACKAGE_SUMMARY "Overlaybd backtore for tcmu")
set(CPACK_RPM_PACKAGE_DESCRIPTION ${CPACK_RPM_PACKAGE_SUMMARY})

set(CPACK_DEBIAN_PACKAGE_VERSION "${PACKAGE_VERSION}-${PACKAGE_RELEASE}")


set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

include(CPack)
